### ISSUE TITLE
`Invalid Gradle JDK configuration found` error with custom java toolchain. 

### ISSUE THREAD

**Issue by sureshg** [JetBrains/gradle-qodana-plugin#7]
Kotlin Gradle project with custom java toolchain fails with `Invalid Gradle JDK configuration found` error. So what's the proper way to run the inspection with java toolchain?

* Gradle config

```
» ./gradlew --version                                                                                                                               

------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          18-loom (Oracle Corporation 18-loom+2-74)
OS:           Mac OS X 11.5.2 x86_64
```

```kotlin
  id("org.jetbrains.qodana") version "0.1.13"
 ....
  toolchain {
    languageVersion.set(JavaLanguageVersion.of("17"))
    vendor.set(JvmVendorSpec.ORACLE)
  }
```

```
2021-09-19 09:20:59,619 [  46187][AWT-EventQueue-0]   INFO - rationStore.ComponentStoreImpl - Saving Project(name=project, containerState=COMPONENT_CREATED, componentStore=/data/project)ExternalSystemProjectTracker took 15 ms, GradleLocalSettings took 11 ms, KotlinCommonCompilerArguments took 13 ms, KotlinScriptingSettings took 91 ms, RunManager took 27 ms, sourceFolderManager took 17 ms 
2021-09-19 09:20:59,848 [  46416][AWT-EventQueue-0]   INFO - plication.impl.ApplicationImpl - LONG VFS PROCESSING. Topic=BulkFileListener, offender=class com.intellij.openapi.vfs.newvfs.AsyncEventSupport$1, message=before, time=141ms 
2021-09-19 09:21:01,135 [  47703][JobScheduler FJ pool 2/6]  ERROR - tion.InspectionApplicationBase - java.lang.IllegalStateException: Gradle project project:15375f63 import failed. 
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Gradle project project:15375f63 import failed.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at org.jetbrains.plugins.gradle.GradleCommandLineProjectConfigurator$StateNotificationListener.waitForImportEnd(GradleCommandLineProjectConfigurator.kt:144)
	at org.jetbrains.plugins.gradle.GradleCommandLineProjectConfigurator.configureProject(GradleCommandLineProjectConfigurator.kt:61)
	at com.intellij.codeInspection.InspectionApplicationBase.configureProject(InspectionApplicationBase.java:447)
	at org.jetbrains.plugins.staticAnalysis.inspections.runner.QodanaRunner.launchInspections(qodana.kt:202)
	at org.jetbrains.plugins.staticAnalysis.inspections.runner.QodanaRunner.launch(qodana.kt:184)
	at org.jetbrains.plugins.staticAnalysis.inspections.runner.QodanaRunner.run(qodana.kt:66)
	at org.jetbrains.plugins.staticAnalysis.inspections.runner.QodanaKt.runAnalysisByQodana(qodana.kt:264)
	at org.jetbrains.plugins.staticAnalysis.inspections.runner.QodanaInspectionApplication.run(QodanaInspectionApplication.kt:56)
	at com.intellij.codeInspection.InspectionApplicationBase.execute(InspectionApplicationBase.java:155)
	at com.intellij.codeInspection.InspectionApplicationBase.startup(InspectionApplicationBase.java:121)
	at com.intellij.codeInspection.InspectionMain.main(InspectionMain.java:108)
	at com.intellij.openapi.application.ApplicationStarter.main(ApplicationStarter.java:49)
	at com.intellij.idea.ApplicationLoader$startApp$3.run(ApplicationLoader.kt:185)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1742)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.IllegalStateException: Gradle project project:15375f63 import failed.
	at org.jetbrains.plugins.gradle.GradleCommandLineProjectConfigurator$StateNotificationListener.onFailure(GradleCommandLineProjectConfigurator.kt:129)
	at com.intellij.openapi.externalSystem.service.remote.ExternalSystemProgressNotificationManagerImpl$TaskListenerWrapper.onFailure(ExternalSystemProgressNotificationManagerImpl.kt:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:120)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:85)
	at com.sun.proxy.$Proxy128.onFailure(Unknown Source)
	at com.intellij.openapi.externalSystem.service.remote.ExternalSystemProgressNotificationManagerImpl$onFailure$1.invoke(ExternalSystemProgressNotificationManagerImpl.kt:65)
	at com.intellij.openapi.externalSystem.service.remote.ExternalSystemProgressNotificationManagerImpl$onFailure$1.invoke(ExternalSystemProgressNotificationManagerImpl.kt:17)
	at com.intellij.openapi.externalSystem.service.remote.ExternalSystemProgressNotificationManagerImpl.forEachListener(ExternalSystemProgressNotificationManagerImpl.kt:90)
	at com.intellij.openapi.externalSystem.service.remote.ExternalSystemProgressNotificationManagerImpl.onFailure(ExternalSystemProgressNotificationManagerImpl.kt:65)
	at com.intellij.openapi.externalSystem.service.internal.ExternalSystemResolveProjectTask.doExecute(ExternalSystemResolveProjectTask.java:107)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:151)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:135)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$2.executeImpl(ExternalSystemUtil.java:566)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$2.lambda$execute$0(ExternalSystemUtil.java:397)
	at com.intellij.openapi.project.DumbServiceHeavyActivities.suspendIndexingAndRun(DumbServiceHeavyActivities.java:21)
	at com.intellij.openapi.project.DumbServiceImpl.suspendIndexingAndRun(DumbServiceImpl.java:187)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$2.execute(ExternalSystemUtil.java:397)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$4.run(ExternalSystemUtil.java:671)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressInCurrentThread$10(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressInCurrentThread(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:394)
	at com.intellij.openapi.progress.Task.queue(Task.java:124)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil.refreshProject(ExternalSystemUtil.java:673)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil.refreshProject(ExternalSystemUtil.java:350)
	at com.intellij.openapi.externalSystem.service.project.autoimport.ProjectAware.reloadProject(ProjectAware.kt:51)
	at com.intellij.openapi.externalSystem.autoimport.AutoImportProjectTracker.refreshProject(AutoImportProjectTracker.kt:150)
	at com.intellij.openapi.externalSystem.autoimport.AutoImportProjectTracker.access$refreshProject(AutoImportProjectTracker.kt:40)
	at com.intellij.openapi.externalSystem.autoimport.AutoImportProjectTracker$scheduleProjectRefresh$1.invoke(AutoImportProjectTracker.kt:88)
	at com.intellij.openapi.externalSystem.autoimport.AutoImportProjectTracker$scheduleProjectRefresh$1.invoke(AutoImportProjectTracker.kt:40)
	at com.intellij.openapi.externalSystem.autoimport.update.PriorityEatUpdate$Companion$invoke$1.run(PriorityEatUpdate.kt:15)
	at com.intellij.util.ui.update.MergingUpdateQueue.queue(MergingUpdateQueue.java:348)
	at com.intellij.openapi.externalSystem.autoimport.AutoImportProjectTracker.scheduleProjectRefresh(AutoImportProjectTracker.kt:87)
	at org.jetbrains.plugins.gradle.GradleCommandLineProjectConfigurator.importProjects(GradleCommandLineProjectConfigurator.kt:77)
	at org.jetbrains.plugins.gradle.GradleCommandLineProjectConfigurator.configureProject(GradleCommandLineProjectConfigurator.kt:60)
	... 20 more
Caused by: com.intellij.openapi.externalSystem.service.execution.ExternalSystemJdkException: Invalid Gradle JDK configuration found. <a href='#open_external_system_settings'>Open Gradle Settings</a> 

	at org.jetbrains.plugins.gradle.service.execution.LocalGradleExecutionAware.jdkConfigurationException(LocalGradleExecutionAware.kt:170)
	at org.jetbrains.plugins.gradle.service.execution.LocalGradleExecutionAware.prepareJvmForExecution(LocalGradleExecutionAware.kt:114)
	at org.jetbrains.plugins.gradle.service.execution.LocalGradleExecutionAware.prepareExecution(LocalGradleExecutionAware.kt:60)
	at com.intellij.openapi.externalSystem.service.internal.ExternalSystemResolveProjectTask.doExecute(ExternalSystemResolveProjectTask.java:90)
	... 51 more
2021-09-19 09:21:01,139 [  47707][JobScheduler FJ pool 2/6]  ERROR - tion.InspectionApplicationBase - IntelliJ IDEA 2021.2.2  Build #IJCA-212.5407 
2021-09-19 09:21:01,140 [  47708][JobScheduler FJ pool 2/6]  ERROR - tion.InspectionApplicationBase - JDK: 11.0.11; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-09-19 09:21:01,141 [  47709][JobScheduler FJ pool 2/6]  ERROR - tion.InspectionApplicationBase - OS: Linux 

```

**Comment by hsz** [comment]
Hey, @sureshg  – I'm closing Issues section in this GitHub repository. I moved your ticket to YouTrack:

QD-1879 Invalid Gradle JDK configuration found error with custom java toolchain
https://youtrack.jetbrains.com/issue/QD-1879
